import 'package:shokutomo/information_format/categories.dart';
import 'package:shokutomo/information_format/product_table.dart';

/*
  ※このファイルをいじらないで下さい
  作成者：ニョン
 */
class DataManagement {
  List<Categories> categories = [
    Categories(no: 1, name: '海産', image: 'assets/img/tuna.png'),
    Categories(no: 2, name: '野菜', image: 'assets/img/brocolli.png'),
    Categories(no: 3, name: '果物', image: 'assets/img/ichigo.png'),
    Categories(no: 4, name: '生肉', image: 'assets/img/beef.png'),
    Categories(no: 5, name: 'お菓子', image: 'assets/img/icecream.png'),
    Categories(no: 6, name: 'おかず', image: 'assets/img/onigiri.png'),
    Categories(no: 7, name: 'ドレッシング', image: 'assets/img/soysauce.png'),
    Categories(no: 8, name: 'ドリンク', image: 'assets/img/fruitjuice.png'),
  ];
  List<Products> products = [
    Products(
        categoryNo: 1,
        no: 1001,
        name: 'エビ',
        bestBy: 3,
        useBy: 4,
        image: 'assets/img/shrimp.png',
        hiragana: 'えび',
        katakana: 'エビ',
        kanji: '海老',
        romaji: 'ebi',
        english: 'shrimp'),
    Products(
        categoryNo: 1,
        no: 1002,
        name: 'サーモン',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/salmon.png',
        hiragana: 'さあもん',
        katakana: 'サーモン',
        kanji: '鮭',
        romaji: 'sa-mon',
        english: 'salmon'),
    Products(
        categoryNo: 1,
        no: 1003,
        name: 'マグロ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/tuna.png',
        hiragana: 'まぐろ',
        katakana: 'マグロ',
        kanji: '鮪',
        romaji: 'maguro',
        english: 'tuna'),
    Products(
        categoryNo: 1,
        no: 1004,
        name: 'カニ',
        bestBy: 3,
        useBy: 4,
        image: 'assets/img/crab.png',
        hiragana: 'かに',
        katakana: 'カニ',
        kanji: '蟹',
        romaji: 'kani',
        english: 'crab'),
    Products(
        categoryNo: 1,
        no: 1005,
        name: 'ホタテ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/scallops.png',
        hiragana: 'ほたて',
        katakana: 'ホタテ',
        kanji: '帆立',
        romaji: 'hotate',
        english: 'scallops'),
    Products(
        categoryNo: 1,
        no: 1006,
        name: 'ムール貝',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/mussels.png',
        hiragana: 'むうるがい',
        katakana: 'ムール貝',
        kanji: 'ムール貝',
        romaji: 'muurugai',
        english: 'mussels'),
    Products(
        categoryNo: 1,
        no: 1007,
        name: 'アサリ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/asari.png',
        hiragana: 'あさり',
        katakana: 'アサリ',
        kanji: 'あさり',
        romaji: 'asari',
        english: 'clam'),
    Products(
        categoryNo: 1,
        no: 1008,
        name: 'カキ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/kaki.png',
        hiragana: 'かき',
        katakana: 'カキ',
        kanji: '牡蠣',
        romaji: 'kaki',
        english: 'oyster'),
    Products(
        categoryNo: 1,
        no: 1009,
        name: 'イカ',
        bestBy: 1,
        useBy: 2,
        image: 'assets/img/ika.png',
        hiragana: 'いか',
        katakana: 'イカ',
        kanji: '烏賊',
        romaji: 'ika',
        english: 'squid'),
    Products(
        categoryNo: 1,
        no: 1010,
        name: 'タラ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/tara.png',
        hiragana: 'たら',
        katakana: 'タラ',
        kanji: '鱈',
        romaji: 'tara',
        english: 'cod'),
    Products(
        categoryNo: 2,
        no: 1011,
        name: 'ニンジン',
        bestBy: 7,
        useBy: 10,
        image: 'assets/img/ninjin.png',
        hiragana: 'にんじん',
        katakana: 'ニンジン',
        kanji: '人参',
        romaji: 'ninjin',
        english: 'carrot'),
    Products(
        categoryNo: 2,
        no: 1012,
        name: 'レタス',
        bestBy: 5,
        useBy: 7,
        image: 'assets/img/lettuce.png',
        hiragana: 'れたす',
        katakana: 'レタス',
        kanji: '',
        romaji: 'retasu',
        english: 'lettuce'),
    Products(
        categoryNo: 2,
        no: 1013,
        name: 'トマト',
        bestBy: 5,
        useBy: 7,
        image: 'assets/img/tomato.png',
        hiragana: 'とまと',
        katakana: 'トマト',
        kanji: '',
        romaji: 'tomato',
        english: 'tomato'),
    Products(
        categoryNo: 2,
        no: 1014,
        name: 'キュウリ',
        bestBy: 5,
        useBy: 7,
        image: 'assets/img/cucumber.png',
        hiragana: 'きゅうり',
        katakana: 'キュウリ',
        kanji: '胡瓜',
        romaji: 'kyuri',
        english: 'cucumber'),
    Products(
        categoryNo: 2,
        no: 1015,
        name: 'パプリカ',
        bestBy: 7,
        useBy: 10,
        image: 'assets/img/bellpepper.png',
        hiragana: 'ぱぷりか',
        katakana: 'パプリカ',
        kanji: '',
        romaji: 'papurika',
        english: 'paprika'),
    Products(
        categoryNo: 2,
        no: 1016,
        name: 'ブロッコリー',
        bestBy: 7,
        useBy: 10,
        image: 'assets/img/brocolli.png',
        hiragana: 'ぶろっこりい',
        katakana: 'ブロッコリー',
        kanji: '',
        romaji: 'burokkorii',
        english: 'broccoli'),
    Products(
        categoryNo: 2,
        no: 1017,
        name: 'ほうれん草',
        bestBy: 3,
        useBy: 5,
        image: 'assets/img/horenso.png',
        hiragana: 'ほうれんそう',
        katakana: 'ホウレンソウ',
        kanji: 'ほうれん草',
        romaji: 'hourensou',
        english: 'spinach'),
    Products(
        categoryNo: 2,
        no: 1018,
        name: 'ズッキーニ',
        bestBy: 5,
        useBy: 7,
        image: 'assets/img/zucchini.png',
        hiragana: 'ずっきいに',
        katakana: 'ズッキーニ',
        kanji: '',
        romaji: 'zukkiini',
        english: 'zucchini'),
    Products(
        categoryNo: 2,
        no: 1019,
        name: 'たまねぎ',
        bestBy: 14,
        useBy: 21,
        image: 'assets/img/onion.png',
        hiragana: 'たまねぎ',
        katakana: 'タマネギ',
        kanji: '玉葱',
        romaji: 'tamanegi',
        english: 'onion'),
    Products(
        categoryNo: 2,
        no: 1020,
        name: 'ジャガイモ',
        bestBy: 30,
        useBy: 60,
        image: 'assets/img/potato.png',
        hiragana: 'じゃがいも',
        katakana: 'ジャガイモ',
        kanji: 'じゃが芋',
        romaji: 'jagaimo',
        english: 'potato'),
    Products(
        categoryNo: 3,
        no: 1021,
        name: 'リンゴ',
        bestBy: 14,
        useBy: 21,
        image: 'assets/img/apple.png',
        hiragana: 'りんご',
        katakana: 'リンゴ',
        kanji: '林檎',
        romaji: 'ringo',
        english: 'apple'),
    Products(
        categoryNo: 3,
        no: 1022,
        name: 'バナナ',
        bestBy: 3,
        useBy: 5,
        image: 'assets/img/banana.png',
        hiragana: 'ばなな',
        katakana: 'バナナ',
        kanji: '',
        romaji: 'banana',
        english: 'banana'),
    Products(
        categoryNo: 3,
        no: 1023,
        name: 'オレンジ',
        bestBy: 7,
        useBy: 10,
        image: 'assets/img/orange.png',
        hiragana: 'おれんじ',
        katakana: 'オレンジ',
        kanji: '',
        romaji: 'orenji',
        english: 'orange'),
    Products(
        categoryNo: 3,
        no: 1024,
        name: 'イチゴ',
        bestBy: 3,
        useBy: 5,
        image: 'assets/img/ichigo.png',
        hiragana: 'いちご',
        katakana: 'イチゴ',
        kanji: '苺',
        romaji: 'ichigo',
        english: 'strawberry'),
    Products(
        categoryNo: 3,
        no: 1025,
        name: 'ぶどう',
        bestBy: 5,
        useBy: 7,
        image: 'assets/img/graped.png',
        hiragana: 'ぶどう',
        katakana: 'ブドウ',
        kanji: '葡萄',
        romaji: 'budou',
        english: 'grape'),
    Products(
        categoryNo: 3,
        no: 1026,
        name: 'パイナップル',
        bestBy: 3,
        useBy: 5,
        image: 'assets/img/pinapple.png',
        hiragana: 'ぱいなっぷる',
        katakana: 'パイナップル',
        kanji: '',
        romaji: 'painappuru',
        english: 'pineapple'),
    Products(
        categoryNo: 3,
        no: 1027,
        name: 'スイカ',
        bestBy: 7,
        useBy: 10,
        image: 'assets/img/watermelon.png',
        hiragana: 'すいか',
        katakana: 'スイカ',
        kanji: '西瓜',
        romaji: 'suika',
        english: 'watermelon'),
    Products(
        categoryNo: 3,
        no: 1028,
        name: 'マンゴー',
        bestBy: 3,
        useBy: 5,
        image: 'assets/img/mango.png',
        hiragana: 'まんごう',
        katakana: 'マンゴー',
        kanji: '',
        romaji: 'mangoo',
        english: 'mango'),
    Products(
        categoryNo: 3,
        no: 1029,
        name: 'もも',
        bestBy: 3,
        useBy: 5,
        image: 'assets/img/peach.png',
        hiragana: 'もも',
        katakana: 'モモ',
        kanji: '桃',
        romaji: 'momo',
        english: 'peach'),
    Products(
        categoryNo: 3,
        no: 1030,
        name: 'プラム',
        bestBy: 5,
        useBy: 7,
        image: 'assets/img/puramu.png',
        hiragana: 'ぷらむ',
        katakana: 'プラム',
        kanji: '',
        romaji: 'puramu',
        english: 'plum'),
    Products(
        categoryNo: 4,
        no: 1031,
        name: '鶏肉',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/chicken.png',
        hiragana: 'とりにく',
        katakana: 'トリニク',
        kanji: '鶏肉',
        romaji: 'toriniku',
        english: 'chicken meat'),
    Products(
        categoryNo: 4,
        no: 1032,
        name: '牛肉',
        bestBy: 3,
        useBy: 5,
        image: 'assets/img/beef.png',
        hiragana: 'ぎゅうにく',
        katakana: 'ギュウニク',
        kanji: '牛肉',
        romaji: 'gyuuniku',
        english: 'beef'),
    Products(
        categoryNo: 4,
        no: 1033,
        name: '豚肉',
        bestBy: 3,
        useBy: 5,
        image: 'assets/img/pork.png',
        hiragana: 'ぶたにく',
        katakana: 'ブタニク',
        kanji: '豚肉',
        romaji: 'butaniku',
        english: 'pork'),
    Products(
        categoryNo: 4,
        no: 1034,
        name: '鴨肉',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/duck.png',
        hiragana: 'かもにく',
        katakana: 'カモニク',
        kanji: '鴨肉',
        romaji: 'kamoniku',
        english: 'duck meat'),
    Products(
        categoryNo: 4,
        no: 1035,
        name: '羊肉',
        bestBy: 3,
        useBy: 5,
        image: 'assets/img/mutton.png',
        hiragana: 'ひつじにく',
        katakana: 'ヒツジニク',
        kanji: '羊肉',
        romaji: 'hitsujiniku',
        english: 'mutton'),
    Products(
        categoryNo: 4,
        no: 1036,
        name: 'ベーコン',
        bestBy: 7,
        useBy: 10,
        image: 'assets/img/bacon.png',
        hiragana: 'べえこん',
        katakana: 'ベーコン',
        kanji: 'ベーコン',
        romaji: 'beekon',
        english: 'bacon'),
    Products(
        categoryNo: 4,
        no: 1037,
        name: 'ソーセージ',
        bestBy: 7,
        useBy: 10,
        image: 'assets/img/sausage.png',
        hiragana: 'そおせえじ',
        katakana: 'ソーセージ',
        kanji: 'ソーセージ',
        romaji: 'sooseeji',
        english: 'sausage'),
    Products(
        categoryNo: 4,
        no: 1038,
        name: 'ステーキ',
        bestBy: 3,
        useBy: 5,
        image: 'assets/img/steak.png',
        hiragana: 'すてえき',
        katakana: 'ステーキ',
        kanji: 'ステーキ',
        romaji: 'suteeki',
        english: 'steak'),
    Products(
        categoryNo: 4,
        no: 1039,
        name: 'ミンチ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/mincemeat.png',
        hiragana: 'みんち',
        katakana: 'ミンチ',
        kanji: 'ミンチ',
        romaji: 'minchi',
        english: 'mince'),
    Products(
        categoryNo: 5,
        no: 1040,
        name: 'チョコレート',
        bestBy: 90,
        useBy: 120,
        image: 'assets/img/chocolate.png',
        hiragana: 'ちょこれえと',
        katakana: 'チョコレート',
        kanji: 'チョコレート',
        romaji: 'chokoreeto',
        english: 'chocolate'),
    Products(
        categoryNo: 5,
        no: 1041,
        name: 'ポテトチップス',
        bestBy: 90,
        useBy: 120,
        image: 'assets/img/potatoeschip.png',
        hiragana: 'ぽてとちっぷす',
        katakana: 'ポテトチップス',
        kanji: 'ポテトチップス',
        romaji: 'potetochippusu',
        english: 'potato chips'),
    Products(
        categoryNo: 5,
        no: 1042,
        name: 'ビスケット',
        bestBy: 90,
        useBy: 120,
        image: 'assets/img/biscuit.png',
        hiragana: 'びすけっと',
        katakana: 'ビスケット',
        kanji: 'ビスケット',
        romaji: 'bisuketto',
        english: 'biscuit'),
    Products(
        categoryNo: 5,
        no: 1043,
        name: 'クッキー',
        bestBy: 90,
        useBy: 120,
        image: 'assets/img/cookies.png',
        hiragana: 'くっきい',
        katakana: 'クッキー',
        kanji: 'クッキー',
        romaji: 'kukkii',
        english: 'cookie'),
    Products(
        categoryNo: 5,
        no: 1044,
        name: 'グミ',
        bestBy: 180,
        useBy: 240,
        image: 'assets/img/gummy.png',
        hiragana: 'ぐみ',
        katakana: 'グミ',
        kanji: 'グミ',
        romaji: 'gumi',
        english: 'gummy'),
    Products(
        categoryNo: 5,
        no: 1045,
        name: 'キャンディ',
        bestBy: 180,
        useBy: 240,
        image: 'assets/img/candy.png',
        hiragana: 'きゃんでぃ',
        katakana: 'キャンディ',
        kanji: 'キャンディ',
        romaji: 'kyandi',
        english: 'candy'),
    Products(
        categoryNo: 5,
        no: 1046,
        name: 'アイスクリーム',
        bestBy: 30,
        useBy: 60,
        image: 'assets/img/icecream.png',
        hiragana: 'あいすくりいむ',
        katakana: 'アイスクリーム',
        kanji: 'アイスクリーム',
        romaji: 'aisukuriimu',
        english: 'ice cream'),
    Products(
        categoryNo: 5,
        no: 1047,
        name: 'パイ',
        bestBy: 3,
        useBy: 5,
        image: 'assets/img/pie.png',
        hiragana: 'ぱい',
        katakana: 'パイ',
        kanji: 'パイ',
        romaji: 'pai',
        english: 'pie'),
    Products(
        categoryNo: 5,
        no: 1048,
        name: 'スナック菓子',
        bestBy: 90,
        useBy: 120,
        image: 'assets/img/snacks.png',
        hiragana: 'すなっくかし',
        katakana: 'スナックカシ',
        kanji: 'スナック菓子',
        romaji: 'sunakkukashi',
        english: 'snack food'),
    Products(
        categoryNo: 5,
        no: 1049,
        name: 'チューインガム',
        bestBy: 365,
        useBy: 365,
        image: 'assets/img/gum.png',
        hiragana: 'ちゅういんがむ',
        katakana: 'チューインガム',
        kanji: 'チューインガム',
        romaji: 'chuuingamu',
        english: 'chewing gum'),
    Products(
        categoryNo: 6,
        no: 1050,
        name: '唐揚げ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/karaage.png',
        hiragana: 'からあげ',
        katakana: 'カラアゲ',
        kanji: '唐揚げ',
        romaji: 'karaage',
        english: 'fried chicken'),
    Products(
        categoryNo: 6,
        no: 1051,
        name: '焼き鳥',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/yakitori.png',
        hiragana: 'やきとり',
        katakana: 'ヤキトリ',
        kanji: '焼き鳥',
        romaji: 'yakitori',
        english: 'yakitori'),
    Products(
        categoryNo: 6,
        no: 1052,
        name: 'おにぎり',
        bestBy: 1,
        useBy: 2,
        image: 'assets/img/onigiri.png',
        hiragana: 'おにぎり',
        katakana: 'オニギリ',
        kanji: 'おにぎり',
        romaji: 'onigiri',
        english: 'rice ball'),
    Products(
        categoryNo: 6,
        no: 1053,
        name: 'お好み焼き',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/okonomiyaki.png',
        hiragana: 'おこのみやき',
        katakana: 'オコノミヤキ',
        kanji: 'お好み焼き',
        romaji: 'okonomiyaki',
        english: ''),
    Products(
        categoryNo: 6,
        no: 1054,
        name: 'サラダ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/salad.png',
        hiragana: 'さらだ',
        katakana: 'サラダ',
        kanji: '',
        romaji: 'sarada',
        english: 'salad'),
    Products(
        categoryNo: 6,
        no: 1055,
        name: '刺身',
        bestBy: 1,
        useBy: 2,
        image: 'assets/img/sashimi.png',
        hiragana: 'さしみ',
        katakana: 'サシミ',
        kanji: '刺身',
        romaji: 'sashimi',
        english: 'sashimi'),
    Products(
        categoryNo: 6,
        no: 1056,
        name: '焼き魚',
        bestBy: 1,
        useBy: 2,
        image: 'assets/img/yakisakana.png',
        hiragana: 'やきざかな',
        katakana: 'ヤキザカナ',
        kanji: '焼き魚',
        romaji: 'yakizakana',
        english: 'grilled fish'),
    Products(
        categoryNo: 8,
        no: 1057,
        name: 'お茶',
        bestBy: 365,
        useBy: 365,
        image: 'assets/img/tea.png',
        hiragana: 'おちゃ',
        katakana: 'オチャ',
        kanji: 'お茶',
        romaji: 'ocha',
        english: 'tea'),
    Products(
        categoryNo: 8,
        no: 1058,
        name: 'コーヒー',
        bestBy: 365,
        useBy: 365,
        image: 'assets/img/coffee.png',
        hiragana: 'こおひい',
        katakana: 'コーヒー',
        kanji: '珈琲',
        romaji: 'koohii',
        english: 'coffee'),
    Products(
        categoryNo: 8,
        no: 1059,
        name: 'ジュース',
        bestBy: 7,
        useBy: 14,
        image: 'assets/img/fruitjuice.png',
        hiragana: 'じゅうす',
        katakana: 'ジュース',
        kanji: '',
        romaji: 'juusu',
        english: 'juice'),
    Products(
        categoryNo: 8,
        no: 1060,
        name: 'スポーツドリンク',
        bestBy: 30,
        useBy: 60,
        image: 'assets/img/sportsdrinks.png',
        hiragana: 'すぽおつどりんく',
        katakana: 'スポーツドリンク',
        kanji: '',
        romaji: 'supootsudorinku',
        english: 'sports drink'),
    Products(
        categoryNo: 8,
        no: 1061,
        name: 'ミネラルウォーター',
        bestBy: 365,
        useBy: 365,
        image: 'assets/img/mineralwater.png',
        hiragana: 'みねらるうぉおたあ',
        katakana: 'ミネラルウォーター',
        kanji: '',
        romaji: 'mineraruuootaa',
        english: 'mineral water'),
    Products(
        categoryNo: 8,
        no: 1062,
        name: 'ビール',
        bestBy: 60,
        useBy: 90,
        image: 'assets/img/beer.png',
        hiragana: 'びいる',
        katakana: 'ビール',
        kanji: '',
        romaji: 'biiru',
        english: 'beer'),
    Products(
        categoryNo: 8,
        no: 1063,
        name: 'ワイン',
        bestBy: 365,
        useBy: 365,
        image: 'assets/img/wine.png',
        hiragana: 'わいん',
        katakana: 'ワイン',
        kanji: '',
        romaji: 'wain',
        english: 'wine'),
    Products(
        categoryNo: 8,
        no: 1064,
        name: '日本酒',
        bestBy: 365,
        useBy: 365,
        image: 'assets/img/sake.png',
        hiragana: 'にほんしゅ',
        katakana: 'ニホンシュ',
        kanji: '日本酒',
        romaji: 'nihonshu',
        english: 'japanese sake'),
    Products(
        categoryNo: 8,
        no: 1065,
        name: 'ウイスキー',
        bestBy: 365,
        useBy: 365,
        image: 'assets/img/whiskey.png',
        hiragana: 'ういすきい',
        katakana: 'ウイスキー',
        kanji: '',
        romaji: 'uisukii',
        english: 'whisky'),
    Products(
        categoryNo: 8,
        no: 1066,
        name: 'ソフトドリンク',
        bestBy: 30,
        useBy: 60,
        image: 'assets/img/soda.png',
        hiragana: 'そふとどりんく',
        katakana: 'ソフトドリンク',
        kanji: '',
        romaji: 'sofutodorinku',
        english: 'soft drink'),
    Products(
        categoryNo: 7,
        no: 1067,
        name: 'サラダドレッシング',
        bestBy: 30,
        useBy: 60,
        image: 'assets/img/saladdressings.png',
        hiragana: 'さらだどれっしんぐ',
        katakana: 'サラダドレッシング',
        kanji: '',
        romaji: 'sarada doresshingu',
        english: 'salad dressing'),
    Products(
        categoryNo: 7,
        no: 1068,
        name: 'ケチャップ',
        bestBy: 90,
        useBy: 180,
        image: 'assets/img/ketchup.png',
        hiragana: 'けちゃっぷ',
        katakana: 'ケチャップ',
        kanji: '',
        romaji: 'kechappu',
        english: 'ketchup'),
    Products(
        categoryNo: 7,
        no: 1069,
        name: 'マヨネーズ',
        bestBy: 90,
        useBy: 180,
        image: 'assets/img/mayonnaise.png',
        hiragana: 'まよねえず',
        katakana: 'マヨネーズ',
        kanji: '',
        romaji: 'mayoneezu',
        english: 'mayonnaise'),
    Products(
        categoryNo: 7,
        no: 1070,
        name: 'ソース',
        bestBy: 90,
        useBy: 180,
        image: 'assets/img/sauce.png',
        hiragana: 'そおす',
        katakana: 'ソース',
        kanji: '',
        romaji: 'soosu',
        english: 'sauce'),
    Products(
        categoryNo: 7,
        no: 1071,
        name: 'ポン酢',
        bestBy: 180,
        useBy: 365,
        image: 'assets/img/ponzu.png',
        hiragana: 'ぽんず',
        katakana: 'ポンズ',
        kanji: 'ポン酢',
        romaji: 'ponzu',
        english: 'ponzu sauce'),
    Products(
        categoryNo: 7,
        no: 1072,
        name: 'おろしポン酢',
        bestBy: 180,
        useBy: 365,
        image: 'assets/img/radishponzu.png',
        hiragana: 'おろしぽんず',
        katakana: 'オロシポンズ',
        kanji: 'おろしポン酢',
        romaji: 'oroshi ponzu',
        english: 'grated ponzu sauce'),
    Products(
        categoryNo: 7,
        no: 1073,
        name: 'ごまだれ',
        bestBy: 30,
        useBy: 60,
        image: 'assets/img/sesame.png',
        hiragana: 'ごまだれ',
        katakana: 'ゴマダレ',
        kanji: 'ごまだれ',
        romaji: 'gomadare',
        english: 'sesame sauce'),
    Products(
        categoryNo: 7,
        no: 1074,
        name: '塩ダレ',
        bestBy: 30,
        useBy: 60,
        image: 'assets/img/salt.png',
        hiragana: 'しおだれ',
        katakana: 'シオダレ',
        kanji: '塩ダレ',
        romaji: 'shio dare',
        english: 'salt sauce'),
    Products(
        categoryNo: 7,
        no: 1075,
        name: 'ポン酢しょうゆ',
        bestBy: 180,
        useBy: 365,
        image: 'assets/img/soysauce.png',
        hiragana: 'ぽんずしょうゆ',
        katakana: 'ポンズショウユ',
        kanji: 'ポン酢しょうゆ',
        romaji: 'ponzu shoyu',
        english: 'ponzu soy sauce'),
    Products(
        categoryNo: 7,
        no: 1076,
        name: '和風ドレッシング',
        bestBy: 30,
        useBy: 60,
        image: 'assets/img/wafu.png',
        hiragana: 'わふうどれっしんぐ',
        katakana: 'ワフードレッシング',
        kanji: '和風ドレッシング',
        romaji: 'wafu doresshingu',
        english: 'japanese style dressing'),
    Products(
        categoryNo: 2,
        no: 1077,
        name: 'アスパラガス',
        bestBy: 14,
        useBy: 14,
        image: 'assets/img/asparagus.png',
        hiragana: '',
        katakana: 'アスパラガス',
        kanji: '',
        romaji: 'asparagus',
        english: 'asparagus'),
    Products(
        categoryNo: 2,
        no: 1078,
        name: 'たけのこ',
        bestBy: 7,
        useBy: 7,
        image: 'assets/img/bamboo-shoot.png',
        hiragana: 'たけのこ',
        katakana: 'タケノコ',
        kanji: '竹の子',
        romaji: 'bamboo-shoot',
        english: 'bambooshoot'),
    Products(
        categoryNo: 2,
        no: 1079,
        name: 'バジル',
        bestBy: 7,
        useBy: 7,
        image: 'assets/img/basil.png',
        hiragana: 'ばじる',
        katakana: 'バジル',
        kanji: '',
        romaji: 'bajiru',
        english: 'basil'),
    Products(
        categoryNo: 2,
        no: 1080,
        name: 'もやし',
        bestBy: 7,
        useBy: 7,
        image: 'assets/img/beanSprouts.png',
        hiragana: 'もやし',
        katakana: 'モヤシ',
        kanji: '',
        romaji: 'moyasi',
        english: 'bean sprouts'),
    Products(
        categoryNo: 2,
        no: 1081,
        name: 'ビートの根',
        bestBy: 30,
        useBy: 30,
        image: 'assets/img/beetroot.png',
        hiragana: 'ビートの根',
        katakana: '',
        kanji: '',
        romaji: 'biitonotane',
        english: 'beetroot'),
    Products(
        categoryNo: 2,
        no: 1082,
        name: 'ししとう',
        bestBy: 7,
        useBy: 7,
        image: 'assets/img/greenPepper.png',
        hiragana: 'ししとうがらし',
        katakana: 'シシトウガラシ',
        kanji: '獅子唐辛子',
        romaji: 'sisitou',
        english: 'green pepper'),
    Products(
        categoryNo: 2,
        no: 1083,
        name: 'ゴーヤ',
        bestBy: 10,
        useBy: 14,
        image: 'assets/img/bitterMelon.png',
        hiragana: 'ごおや',
        katakana: 'ゴーヤ',
        kanji: '',
        romaji: 'gooya',
        english: 'bitter melon'),
    Products(
        categoryNo: 2,
        no: 1084,
        name: 'そら豆',
        bestBy: 7,
        useBy: 7,
        image: 'assets/img/broad-beans.png',
        hiragana: 'そらまめ',
        katakana: 'ソラマメ',
        kanji: '空豆',
        romaji: 'soramame',
        english: 'broad beans'),
    Products(
        categoryNo: 2,
        no: 1085,
        name: 'カリフラワー',
        bestBy: 7,
        useBy: 14,
        image: 'assets/img/cauliflower.png',
        hiragana: 'かりふらわあ',
        katakana: 'カリフラワー',
        kanji: '',
        romaji: 'karifurawa',
        english: 'cauliflower'),
    Products(
        categoryNo: 2,
        no: 1086,
        name: 'セロリ',
        bestBy: 7,
        useBy: 14,
        image: 'assets/img/celery.png',
        hiragana: 'せろり',
        katakana: 'セロリ',
        kanji: '',
        romaji: 'serori',
        english: 'celery'),
    Products(
        categoryNo: 2,
        no: 1087,
        name: '唐辛子',
        bestBy: 100,
        useBy: 180,
        image: 'assets/img/chili-pepper.png',
        hiragana: 'とうがらし',
        katakana: 'トウガラシ',
        kanji: '唐辛子',
        romaji: 'tougarasi',
        english: 'chili pepper'),
    Products(
        categoryNo: 2,
        no: 1088,
        name: '白菜',
        bestBy: 7,
        useBy: 14,
        image: 'assets/img/chineseCabbage.png',
        hiragana: 'はくさい',
        katakana: 'ハクサイ',
        kanji: '白菜',
        romaji: 'hakusai',
        english: 'chinese cabbage'),
    Products(
        categoryNo: 2,
        no: 1089,
        name: 'ニラ',
        bestBy: 7,
        useBy: 14,
        image: 'assets/img/chineseChive.png',
        hiragana: 'にら',
        katakana: 'ニラ',
        kanji: '',
        romaji: 'nira',
        english: 'chinese chive'),
    Products(
        categoryNo: 2,
        no: 1090,
        name: 'セリ',
        bestBy: 7,
        useBy: 7,
        image: 'assets/img/dropwort.png',
        hiragana: 'せり',
        katakana: 'セリ',
        kanji: '',
        romaji: 'seri',
        english: 'dropwort'),
    Products(
        categoryNo: 2,
        no: 1091,
        name: 'ごぼう',
        bestBy: 7,
        useBy: 14,
        image: 'assets/img/edibleBurdock.png',
        hiragana: 'ごぼう',
        katakana: 'ゴボウ',
        kanji: '',
        romaji: 'gobou',
        english: 'edible burdock'),
    Products(
        categoryNo: 2,
        no: 1092,
        name: '茄子',
        bestBy: 7,
        useBy: 7,
        image: 'assets/img/eggplant.png',
        hiragana: 'なす',
        katakana: 'ナス',
        kanji: '茄子',
        romaji: 'nasu',
        english: 'eggplant'),
    Products(
        categoryNo: 2,
        no: 1093,
        name: 'えのき茸',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/enoki-mushroom.png',
        hiragana: 'えのきたけ',
        katakana: 'エノキダケ',
        kanji: 'えのき茸',
        romaji: 'enokidake',
        english: 'enoki mushroom'),
    Products(
        categoryNo: 2,
        no: 1094,
        name: 'さやえんどう',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/gardenPea.png',
        hiragana: 'さやえんどう',
        katakana: 'サヤエンドウ',
        kanji: '',
        romaji: 'sayaendo',
        english: 'gardenPea'),
    Products(
        categoryNo: 2,
        no: 1095,
        name: '春菊',
        bestBy: 7,
        useBy: 14,
        image: 'assets/img/garlandChrysanthemum.png',
        hiragana: 'しゅんぎく',
        katakana: 'シュンギク',
        kanji: '春菊',
        romaji: 'shungiku',
        english: 'garland chrysanthemum'),
    Products(
        categoryNo: 2,
        no: 1096,
        name: 'みょうが',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/japaneseWildGinger.png',
        hiragana: 'みょうが',
        katakana: 'ミョウガ',
        kanji: '',
        romaji: 'myouga',
        english: 'japaneseWild ginger'),
    Products(
        categoryNo: 2,
        no: 1097,
        name: 'エリンギ',
        bestBy: 7,
        useBy: 14,
        image: 'assets/img/KingTrumpetMushroom.png',
        hiragana: 'えりんぎ',
        katakana: 'エリンギ',
        kanji: '',
        romaji: 'eringi',
        english: 'king trumpet mushroom'),
    Products(
        categoryNo: 2,
        no: 1098,
        name: '木耳',
        bestBy: 365,
        useBy: 700,
        image: 'assets/img/cloudEarMushroom.png',
        hiragana: 'きくらげ',
        katakana: 'キクラゲ',
        kanji: '木耳',
        romaji: 'kikurage',
        english: 'cloud ear mushroom'),
    Products(
        categoryNo: 2,
        no: 1099,
        name: 'コリアンダー',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/coriander.png',
        hiragana: 'こりあんだ',
        katakana: 'コリアンダー',
        kanji: '',
        romaji: 'koriandaa',
        english: 'coriander'),
    Products(
        categoryNo: 2,
        no: 1100,
        name: 'ふき',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/butterbur.png',
        hiragana: 'ふき',
        katakana: 'フキ',
        kanji: '',
        romaji: 'fuki',
        english: 'butterbur'),
    Products(
        categoryNo: 2,
        no: 1101,
        name: 'ふきのとう',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/butterburScapes.png',
        hiragana: 'ふきのとう',
        katakana: 'フキノトウ',
        kanji: '',
        romaji: 'fukinotou',
        english: 'butterbur scapes'),
    Products(
        categoryNo: 3,
        no: 1102,
        name: 'アボカド',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/avocado.png',
        hiragana: 'あぼかど',
        katakana: 'アボカド',
        kanji: '',
        romaji: 'abokado',
        english: 'avocado'),
    Products(
        categoryNo: 3,
        no: 1103,
        name: '木イチゴ',
        bestBy: 7,
        useBy: 14,
        image: 'assets/img/raspberry.png',
        hiragana: 'きいちご',
        katakana: 'ラズベリー',
        kanji: '',
        romaji: 'kiichigo',
        english: 'raspberry'),
    Products(
        categoryNo: 3,
        no: 1104,
        name: 'グレープフルーツ',
        bestBy: 100,
        useBy: 100,
        image: 'assets/img/grapefruit.png',
        hiragana: 'ぐれーぷふるーつ',
        katakana: 'グレープフルーツ',
        kanji: '',
        romaji: 'gure-pufuru-tu',
        english: 'grapefruit'),
    Products(
        categoryNo: 3,
        no: 1105,
        name: 'ココナッツ',
        bestBy: 3,
        useBy: 14,
        image: 'assets/img/coconut.png',
        hiragana: 'ここなっつ',
        katakana: 'ココナッツ',
        kanji: '',
        romaji: 'kokonattu',
        english: 'coconut'),
    Products(
        categoryNo: 3,
        no: 1106,
        name: 'さくらんぼ',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/cherry.png',
        hiragana: 'さくらんぼ',
        katakana: 'チェリー',
        kanji: '桜桃',
        romaji: 'sakuranbo',
        english: 'cherry'),
    Products(
        categoryNo: 3,
        no: 1107,
        name: 'パパイヤ',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/papaya.png',
        hiragana: 'ぱぱいや',
        katakana: 'パパイヤ',
        kanji: '',
        romaji: 'papaiya',
        english: 'papaya'),
    Products(
        categoryNo: 3,
        no: 1108,
        name: 'プラム',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/plum.png',
        hiragana: 'すもも',
        katakana: 'プラム',
        kanji: '李',
        romaji: 'puramu',
        english: 'plum'),
    Products(
        categoryNo: 3,
        no: 1109,
        name: 'ブルーベリー',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/blueberry.png',
        hiragana: 'ぶるーべりー',
        katakana: 'ブルーベリー',
        kanji: '',
        romaji: 'buru-beri-',
        english: 'blueberry'),
    Products(
        categoryNo: 3,
        no: 1110,
        name: 'マスカット',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/muscat.png',
        hiragana: 'ますかっと',
        katakana: 'マスカット',
        kanji: '',
        romaji: 'masukatto',
        english: 'muscat'),
    Products(
        categoryNo: 3,
        no: 1111,
        name: 'ライム',
        bestBy: 3,
        useBy: 14,
        image: 'assets/img/lime.png',
        hiragana: 'らいむ',
        katakana: 'ライム',
        kanji: '',
        romaji: 'raimu',
        english: 'lime'),
    Products(
        categoryNo: 3,
        no: 1112,
        name: 'あんず',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/apricot.png',
        hiragana: 'あんず',
        katakana: 'アンズ',
        kanji: '杏子',
        romaji: 'anzu',
        english: 'apricot'),
    Products(
        categoryNo: 3,
        no: 1113,
        name: 'イチジク',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/fig.png',
        hiragana: 'いちじく',
        katakana: 'イチジク',
        kanji: '無花果',
        romaji: 'itijiku',
        english: 'fig'),
    Products(
        categoryNo: 3,
        no: 1114,
        name: '柿',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/persimmon.png',
        hiragana: 'かき',
        katakana: 'カキ',
        kanji: '柿',
        romaji: 'kaki',
        english: 'persimmon'),
    Products(
        categoryNo: 3,
        no: 1115,
        name: '栗',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/chestnut.png',
        hiragana: 'くり',
        katakana: 'クリ',
        kanji: '栗',
        romaji: 'kuri',
        english: 'chestnut'),
    Products(
        categoryNo: 3,
        no: 1116,
        name: '梨',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/pear.png',
        hiragana: 'なし',
        katakana: 'ナシ',
        kanji: '梨',
        romaji: 'nasi',
        english: 'pear'),
    Products(
        categoryNo: 3,
        no: 1117,
        name: 'びわ',
        bestBy: 4,
        useBy: 7,
        image: 'assets/img/loquat.png',
        hiragana: 'びわ',
        katakana: 'ビワ',
        kanji: '枇杷',
        romaji: 'biwa',
        english: 'loquat'),
    Products(
        categoryNo: 1,
        no: 1119,
        name: 'タコ',
        bestBy: 3,
        useBy: 4,
        image: 'assets/img/octopus.png',
        hiragana: 'たこ',
        katakana: 'タコ',
        kanji: '蛸',
        romaji: 'tako',
        english: 'octopus'),
    Products(
        categoryNo: 1,
        no: 1120,
        name: 'サザエ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/turban shell.png',
        hiragana: 'さざえ',
        katakana: 'サザエ',
        kanji: '栄螺',
        romaji: 'sazae',
        english: 'turban shell'),
    Products(
        categoryNo: 1,
        no: 1121,
        name: 'アワビ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/abalone.png',
        hiragana: 'あわび',
        katakana: 'アワビ',
        kanji: '鮑',
        romaji: 'awabi',
        english: 'abalone'),
    Products(
        categoryNo: 1,
        no: 1122,
        name: 'ウニ',
        bestBy: 1,
        useBy: 2,
        image: 'assets/img/sea urchin.png',
        hiragana: 'うに',
        katakana: 'ウニ',
        kanji: '海胆',
        romaji: 'uni',
        english: 'sea urchin'),
    Products(
        categoryNo: 1,
        no: 1123,
        name: 'シャコ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/mantis shrimp.png',
        hiragana: 'しゃこ',
        katakana: 'シャコ',
        kanji: '蝦蛄',
        romaji: 'shako',
        english: 'mantis shrimp'),
    Products(
        categoryNo: 1,
        no: 1124,
        name: 'アジ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/horse mackerel.png',
        hiragana: 'あじ',
        katakana: 'アジ',
        kanji: '鯵',
        romaji: 'aji',
        english: 'horse mackerel'),
    Products(
        categoryNo: 1,
        no: 1125,
        name: 'サワラ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/spanish mackerel.png',
        hiragana: 'さわら',
        katakana: 'サワラ',
        kanji: '鰆',
        romaji: 'sawara',
        english: 'spanish mackerel'),
    Products(
        categoryNo: 1,
        no: 1126,
        name: 'イワシ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/sardine.png',
        hiragana: 'いわし',
        katakana: 'イワシ',
        kanji: '鰯',
        romaji: 'iwasi',
        english: 'sardine'),
    Products(
        categoryNo: 1,
        no: 1127,
        name: 'ハマチ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/yellowtail.png',
        hiragana: 'はまち',
        katakana: 'ハマチ',
        kanji: '魬',
        romaji: 'hamati',
        english: 'yellowtail'),
    Products(
        categoryNo: 1,
        no: 1128,
        name: 'カツオ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/bonito.png',
        hiragana: 'かつお',
        katakana: 'カツオ',
        kanji: '鰹',
        romaji: 'katuo',
        english: 'bonito'),
    Products(
        categoryNo: 1,
        no: 1129,
        name: 'サンマ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/pacific saury.png',
        hiragana: 'さんま',
        katakana: 'サンマ',
        kanji: '秋刀魚',
        romaji: 'sanma',
        english: 'pacific saury'),
    Products(
        categoryNo: 1,
        no: 1130,
        name: 'シーラカンス',
        bestBy: 3,
        useBy: 4,
        image: 'assets/img/coelacanth.png',
        hiragana: 'しーらかんす',
        katakana: 'シーラカンス',
        kanji: '',
        romaji: 'si-rakansu',
        english: 'coelacanth'),
    Products(
        categoryNo: 1,
        no: 1131,
        name: 'ヒラメ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/halibut.png',
        hiragana: 'ひらめ',
        katakana: 'ヒラメ',
        kanji: '平目',
        romaji: 'hirame',
        english: 'halibut'),
    Products(
        categoryNo: 1,
        no: 1132,
        name: 'フグ',
        bestBy: 1,
        useBy: 2,
        image: 'assets/img/pufferfish.png',
        hiragana: 'ふぐ',
        katakana: 'フグ',
        kanji: '河豚',
        romaji: 'fugu',
        english: 'puffer fish'),
    Products(
        categoryNo: 1,
        no: 1133,
        name: 'オイスター',
        bestBy: 1,
        useBy: 2,
        image: 'assets/img/oyster.png',
        hiragana: 'おいすたー',
        katakana: 'オイスター',
        kanji: '牡蠣',
        romaji: 'oisuta-',
        english: 'oyster'),
    Products(
        categoryNo: 1,
        no: 1134,
        name: 'タラバガニ',
        bestBy: 1,
        useBy: 2,
        image: 'assets/img/king crab.png',
        hiragana: 'たらばがに',
        katakana: 'タラバガニ',
        kanji: '鱈蟹',
        romaji: 'tarabagani',
        english: 'king crab'),
    Products(
        categoryNo: 1,
        no: 1135,
        name: 'イセエビ',
        bestBy: 1,
        useBy: 2,
        image: 'assets/img/spiny lobster.png',
        hiragana: 'いせえび',
        katakana: 'イセエビ',
        kanji: '伊勢海老',
        romaji: 'iseebi',
        english: 'spiny lobster'),
    Products(
        categoryNo: 1,
        no: 1136,
        name: 'クラゲ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/lobster.png',
        hiragana: 'くらげ',
        katakana: 'クラゲ',
        kanji: '海月',
        romaji: 'furage',
        english: 'lobster'),
    Products(
        categoryNo: 1,
        no: 1137,
        name: 'ウミウシ',
        bestBy: 1,
        useBy: 2,
        image: 'assets/img/sea slug.png',
        hiragana: 'うみうし',
        katakana: 'ウミウシ',
        kanji: '海牛',
        romaji: 'umiusi',
        english: 'sea slug'),
    Products(
        categoryNo: 1,
        no: 1138,
        name: 'ドジョウ',
        bestBy: 1,
        useBy: 2,
        image: 'assets/img/weather loach.png',
        hiragana: 'どじょう',
        katakana: 'ドジョウ',
        kanji: '泥鰌',
        romaji: 'dojyou',
        english: 'weather loach'),
    Products(
        categoryNo: 5,
        no: 1139,
        name: 'ケーキ',
        bestBy: 3,
        useBy: 5,
        image: 'assets/img/cake.png',
        hiragana: 'けえき',
        katakana: 'ケーキ',
        kanji: '',
        romaji: 'ke-ki',
        english: 'cake'),
    Products(
        categoryNo: 5,
        no: 1140,
        name: 'マシュマロ',
        bestBy: 365,
        useBy: 365,
        image: 'assets/img/marshmallow.png',
        hiragana: 'ましゅまろ',
        katakana: 'マシュマロ',
        kanji: '',
        romaji: 'mashumaro',
        english: 'marshmallow'),
    Products(
        categoryNo: 5,
        no: 1141,
        name: 'ポップコーン',
        bestBy: 365,
        useBy: 365,
        image: 'assets/img/popcorn.png',
        hiragana: 'ぽっぷこーん',
        katakana: 'ポップコーン',
        kanji: '',
        romaji: 'poppuko-n',
        english: 'popcorn'),
    Products(
        categoryNo: 5,
        no: 1142,
        name: 'ドーナツ',
        bestBy: 1,
        useBy: 2,
        image: 'assets/img/donut.png',
        hiragana: 'どーなっつ',
        katakana: 'ドーナツ',
        kanji: '',
        romaji: 'do-nattu',
        english: 'donut'),
    Products(
        categoryNo: 5,
        no: 1143,
        name: 'プリン',
        bestBy: 3,
        useBy: 7,
        image: 'assets/img/pudding.png',
        hiragana: 'ぷりん',
        katakana: 'プリン',
        kanji: '',
        romaji: 'purin',
        english: 'pudding'),
    Products(
        categoryNo: 5,
        no: 1144,
        name: 'クリームパン',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/cream pan.png',
        hiragana: 'くりーむぱん',
        katakana: 'クリームパン',
        kanji: '',
        romaji: 'kuri-mupan',
        english: 'cream pan'),
    Products(
        categoryNo: 5,
        no: 1145,
        name: 'スイスロール',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/swiss roll.png',
        hiragana: 'すいすろーる',
        katakana: 'スイスロール',
        kanji: '',
        romaji: 'suisuro-ru',
        english: 'swiss roll'),
    Products(
        categoryNo: 5,
        no: 1146,
        name: 'パフェ',
        bestBy: 1,
        useBy: 1,
        image: 'assets/img/parfait.png',
        hiragana: 'ぱふぇ',
        katakana: 'パフェ',
        kanji: '',
        romaji: 'pafe',
        english: 'parfait'),
    Products(
        categoryNo: 5,
        no: 1147,
        name: 'シュークリーム',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/cream puff.png',
        hiragana: 'しゅーくりーむ',
        katakana: 'シュークリーム',
        kanji: '',
        romaji: 'shu-kuri-mu',
        english: 'cream puff'),
    Products(
        categoryNo: 5,
        no: 1148,
        name: 'マカロン',
        bestBy: 7,
        useBy: 14,
        image: 'assets/img/macaron.png',
        hiragana: 'まかろん',
        katakana: 'マカロン',
        kanji: '',
        romaji: 'makaron',
        english: 'macaron'),
    Products(
        categoryNo: 5,
        no: 1149,
        name: 'ゼリービーンズ',
        bestBy: 365,
        useBy: 365,
        image: 'assets/img/jelly beans.png',
        hiragana: 'ぜりーびーんず',
        katakana: 'ゼリービーンズ',
        kanji: '',
        romaji: 'zeri-bi-nzu',
        english: 'jelly beans'),
    Products(
        categoryNo: 5,
        no: 1150,
        name: 'チョコレートバー',
        bestBy: 150,
        useBy: 365,
        image: 'assets/img/chocolate bar.png',
        hiragana: 'ちょこれーとばー',
        katakana: 'チョコレートバー',
        kanji: '',
        romaji: 'chokore-toba-',
        english: 'chocolate bar'),
    Products(
        categoryNo: 5,
        no: 1151,
        name: 'ワッフル',
        bestBy: 5,
        useBy: 7,
        image: 'assets/img/waffle.png',
        hiragana: 'わっふる',
        katakana: 'ワッフル',
        kanji: '',
        romaji: 'waffuru',
        english: 'waffle'),
    Products(
        categoryNo: 5,
        no: 1152,
        name: 'パンケーキ',
        bestBy: 5,
        useBy: 7,
        image: 'assets/img/pancake.png',
        hiragana: 'ぱんけーき',
        katakana: 'パンケーキ',
        kanji: '',
        romaji: 'panke-ki',
        english: 'pancake'),
    Products(
        categoryNo: 5,
        no: 1153,
        name: 'クレープ',
        bestBy: 5,
        useBy: 7,
        image: 'assets/img/crepes.png',
        hiragana: 'くれーぷ',
        katakana: 'クレープ',
        kanji: '',
        romaji: 'kure-pu',
        english: 'crepes'),
    Products(
        categoryNo: 5,
        no: 1154,
        name: 'プレッツェル',
        bestBy: 150,
        useBy: 365,
        image: 'assets/img/pretzel.png',
        hiragana: 'ぷれっしぇる',
        katakana: 'プレッツェル',
        kanji: '',
        romaji: 'puressheru',
        english: 'pretzel'),
    Products(
        categoryNo: 5,
        no: 1155,
        name: 'ショートケーキ',
        bestBy: 5,
        useBy: 7,
        image: 'assets/img/shortcake.png',
        hiragana: 'しょーとけーき',
        katakana: 'ショートケーキ',
        kanji: '',
        romaji: 'sho-toke-ki',
        english: 'shortcake'),
    Products(
        categoryNo: 5,
        no: 1156,
        name: 'ジャム',
        bestBy: 365,
        useBy: 365,
        image: 'assets/img/jam.png',
        hiragana: 'じゃむ',
        katakana: 'ジャム',
        kanji: '',
        romaji: 'jamu',
        english: 'jam'),
    Products(
        categoryNo: 5,
        no: 1157,
        name: 'アップルパイ',
        bestBy: 5,
        useBy: 7,
        image: 'assets/img/apple pie.png',
        hiragana: 'あっぷるぱい',
        katakana: 'アップルパイ',
        kanji: '',
        romaji: 'appurupai',
        english: 'apple pie'),
    Products(
        categoryNo: 5,
        no: 1158,
        name: 'ラムネ',
        bestBy: 150,
        useBy: 365,
        image: 'assets/img/ramune.png',
        hiragana: 'らむね',
        katakana: 'ラムネ',
        kanji: '',
        romaji: 'ramune',
        english: ''),
    Products(
        categoryNo: 5,
        no: 1159,
        name: 'ピーナッツバタークッキー',
        bestBy: 14,
        useBy: 30,
        image: 'assets/img/peanut butter cookie.png',
        hiragana: 'ぴーなっつばたーくっきー',
        katakana: 'ピーナッツバタークッキー',
        kanji: '',
        romaji: 'pi-nattubata-kukki-',
        english: 'peanut butter cookie'),
    Products(
        categoryNo: 6,
        no: 1160,
        name: 'オムライス',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/omuraisu.png',
        hiragana: 'おむらいす',
        katakana: 'オムライス',
        kanji: '',
        romaji: 'omuraisu',
        english: 'omelette rice'),
    Products(
        categoryNo: 6,
        no: 1161,
        name: 'ハンバーグ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/hamburger.png',
        hiragana: 'はんばーぐ',
        katakana: 'ハンバーグ',
        kanji: '',
        romaji: 'hanba-gu',
        english: 'hamburger'),
    Products(
        categoryNo: 6,
        no: 1162,
        name: 'カレーライス',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/careraisu.png',
        hiragana: 'かれーらいす',
        katakana: 'カレーライス',
        kanji: '',
        romaji: 'care-raisu',
        english: 'curry rice'),
    Products(
        categoryNo: 6,
        no: 1163,
        name: '焼き肉',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/yakiniku.png',
        hiragana: 'やきにく',
        katakana: 'ヤキニク',
        kanji: '焼肉',
        romaji: 'yakiniku',
        english: ''),
    Products(
        categoryNo: 6,
        no: 1164,
        name: '焼きそば',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/yakisoba.png',
        hiragana: 'やきそば',
        katakana: 'ヤキソバ',
        kanji: '焼きそば',
        romaji: 'yakisoba',
        english: 'fried noodles'),
    Products(
        categoryNo: 6,
        no: 1165,
        name: 'グラタン',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/gratin.png',
        hiragana: 'ぐらたん',
        katakana: 'グラタン',
        kanji: '',
        romaji: 'guratan',
        english: 'gratin'),
    Products(
        categoryNo: 6,
        no: 1166,
        name: '餃子',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/gyoza.png',
        hiragana: 'ぎょうざ',
        katakana: 'ギョウザ',
        kanji: '餃子',
        romaji: 'gyoza',
        english: 'chinese dumpling'),
    Products(
        categoryNo: 6,
        no: 1167,
        name: '味噌汁',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/miso soup.png',
        hiragana: 'みそしる',
        katakana: 'ミソシル',
        kanji: '味噌汁',
        romaji: 'misosiru',
        english: 'miso soup'),
    Products(
        categoryNo: 6,
        no: 1168,
        name: 'ステーキ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/steak.png',
        hiragana: 'すてーき',
        katakana: 'ステーキ',
        kanji: '',
        romaji: 'sute-ki',
        english: 'steak'),
    Products(
        categoryNo: 6,
        no: 1169,
        name: 'カツ丼',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/katsudon.png',
        hiragana: 'かつどん',
        katakana: 'カツドン',
        kanji: 'カツ丼',
        romaji: 'katsudon',
        english: 'pork cutlet on rice'),
    Products(
        categoryNo: 6,
        no: 1170,
        name: 'たこ焼き',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/takoyaki.png',
        hiragana: 'たこやき',
        katakana: 'タコヤキ',
        kanji: 'たこ焼き',
        romaji: 'takoyaki',
        english: ''),
    Products(
        categoryNo: 6,
        no: 1171,
        name: 'カニクリームコロッケ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/kanikuri-mukorokke.png',
        hiragana: 'かにくりーむころっけ',
        katakana: 'カニクリームコロッケ',
        kanji: '',
        romaji: 'kanikuri-mukorokke',
        english: 'crab cream croquette'),
    Products(
        categoryNo: 6,
        no: 1172,
        name: '焼売',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/shumai.png',
        hiragana: 'しゅうまい',
        katakana: 'シュウマイ',
        kanji: '焼売',
        romaji: 'shumai',
        english: ''),
    Products(
        categoryNo: 6,
        no: 1173,
        name: 'ピザ',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/pizza.png',
        hiragana: 'ぴざ',
        katakana: 'ピザ',
        kanji: '',
        romaji: 'piza',
        english: 'pizza'),
    Products(
        categoryNo: 6,
        no: 1174,
        name: '鯖の塩焼き',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/sabashioyaki.png',
        hiragana: 'さばのしおやき',
        katakana: 'サバノシオヤキ',
        kanji: '鯖の塩焼き',
        romaji: 'sabashioyaki',
        english: 'salt-grilled mackerel'),
    Products(
        categoryNo: 6,
        no: 1175,
        name: 'フライドチキン',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/fried chicken.png',
        hiragana: 'ふらいどちきん',
        katakana: 'フライドチキン',
        kanji: '',
        romaji: 'furaidotikin',
        english: 'fried chicken'),
    Products(
        categoryNo: 6,
        no: 1176,
        name: 'ミートボール',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/meatball.png',
        hiragana: 'みーとぼーる',
        katakana: 'ミートボール',
        kanji: '',
        romaji: 'mi-tobo-ru',
        english: 'meatball'),
    Products(
        categoryNo: 6,
        no: 1177,
        name: '野菜炒め',
        bestBy: 2,
        useBy: 3,
        image: 'assets/img/yasaiitame.png',
        hiragana: 'やさいいため',
        katakana: 'ヤサイイタメ',
        kanji: '野菜炒め',
        romaji: 'yasaiitame',
        english: 'fried vegetables'),
    Products(
        categoryNo: 6,
        no: 1178,
        name: '豆腐',
        bestBy: 6,
        useBy: 10,
        image: 'assets/img/toufu.png',
        hiragana: 'とうふ',
        katakana: 'トウフ',
        kanji: '豆腐',
        romaji: 'toufu',
        english: 'tofu'),
    Products(
        categoryNo: 6,
        no: 1179,
        name: 'キムチ',
        bestBy: 30,
        useBy: 30,
        image: 'assets/img/kimuti.png',
        hiragana: 'きむち',
        katakana: 'キムチ',
        kanji: '',
        romaji: 'kimuti',
        english: 'kimchi'),
    Products(
        categoryNo: 6,
        no: 1180,
        name: '卵',
        bestBy: 14,
        useBy: 14,
        image: 'assets/img/tamago.png',
        hiragana: 'たまご',
        katakana: 'タマゴ',
        kanji: '卵',
        romaji: 'tamago',
        english: 'egg'),
    Products(
        categoryNo: 1,
        no: 1181,
        name: 'うなぎ',
        bestBy: 3,
        useBy: 5,
        image: 'assets/img/eel.png',
        hiragana: 'うなぎ',
        katakana: 'ウナギ',
        kanji: '鰻',
        romaji: 'unagi',
        english: 'eel'),
    Products(
        categoryNo: 2,
        no: 1182,
        name: 'キャベツ',
        bestBy: 14,
        useBy: 21,
        image: 'assets/img/cabbage.png',
        hiragana: 'きゃべつ',
        katakana: 'キャベツ',
        kanji: '',
        romaji: 'kyabetu',
        english: 'cabbage'),
    Products(
        categoryNo: 1,
        no: 1183,
        name: '牛乳',
        bestBy: 3,
        useBy: 5,
        image: 'assets/img/milk.png',
        hiragana: 'ぎゅうにゅう',
        katakana: 'ギュウニュウ',
        kanji: '牛乳',
        romaji: 'gyuunyuu',
        english: 'milk'),
  ];

  List<Categories> getCategories() {
    return categories;
  }

  List<Products> getProducts() {
    return products;
  }
}
