// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW2H8ldPl8-71ASjGyhilTHTJfo6sP44Y',
    appId: '1:917672187801:web:15a7bbf8ac596e036f6508',
    messagingSenderId: '917672187801',
    projectId: 'shokutomo-1d684',
    authDomain: 'shokutomo-1d684.firebaseapp.com',
    databaseURL: 'https://shokutomo-1d684-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shokutomo-1d684.appspot.com',
    measurementId: 'G-10PZX0TQ45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4XAn90RSC6lRlm3rooYF9pyJHZ11Aud8',
    appId: '1:917672187801:android:8cee45d4d991bc0b6f6508',
    messagingSenderId: '917672187801',
    projectId: 'shokutomo-1d684',
    databaseURL: 'https://shokutomo-1d684-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shokutomo-1d684.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh0V0IYdBSXEeuPH4ZZJPSusGBUgptq6o',
    appId: '1:917672187801:ios:850f8716ae979e3f6f6508',
    messagingSenderId: '917672187801',
    projectId: 'shokutomo-1d684',
    databaseURL: 'https://shokutomo-1d684-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shokutomo-1d684.appspot.com',
    iosBundleId: 'com.example.shokutomo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh0V0IYdBSXEeuPH4ZZJPSusGBUgptq6o',
    appId: '1:917672187801:ios:84fe83ba1e17e3f46f6508',
    messagingSenderId: '917672187801',
    projectId: 'shokutomo-1d684',
    databaseURL: 'https://shokutomo-1d684-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'shokutomo-1d684.appspot.com',
    iosBundleId: 'com.example.shokutomo.RunnerTests',
  );
}
